changelog:
  exclude:
    labels:
      - dependencies
      - skip-changelog
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Internal
      labels:
        - chore
        - refactor
        - test

